#!/usr/bin/env bash

set -eu

vagrant init bento/centos-7.1

if [ ! `which virtualbox` ]; then
  echo Install virtualbox
  brew cask install virtualbox
fi

if [ ! `which vagrant` ]; then
  echo Install vagrant
  brew cask install vagrant
  echo Install vagrant-manager
  brew cask install vagrant-manager
fi

if [ ! `which ansible` ]; then
  echo Install ansible
  brew install ansible
fi

if [ ! `which bundler` ]; then
  gem install bundler
fi

echo Install vagrant-global-status of vagrant-global-status
vagrant plugin install vagrant-global-status
echo Install vagrant-global-status of vagrant-global-status
vagrant plugin install vagrant-share --plugin-version 1.1.8
